### ISSUE TITLE
Use Database Button

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/CRUD-PROJECT#20]
**Describe the bug**
The use database button is redirecting me on the create database window

**To Reproduce**
1. Go to 'Database Window'
2. Click on 'Use Database to an existing database'
3. See error

**Expected behavior**
It should have opened the existing database

*Desktop (please complete the following information):*
 - OS: Windows
 - Browser: Chrome
 - Version: 10

*Smartphone (please complete the following information):*
 - Device: Xiaomi Note 10
 - OS: Android
 - Browser Chrome
 - Version 9.0

**Additional context**
This usually happens on the first run of the program but whenever you exit and rerun the application it would work fine.  And on the second run, the use button would work as intended.

**Comment by BeepBoopBit** [comment]
The said bug was caused by the problem between the "Create Database Window." It is Now Fix
