### ISSUE TITLE
Delete Database and Use Database Buttons 

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/CRUD-PROJECT#21]
**Describe the bug**
There are instances when I deleted an existing database and try to use another database that is closed to the one that I deleted. Sometimes it would still run the deleted database rather than the one that I clicked on. 

**To Reproduce**
1. Go to 'Database Window'
2. Click on 'Delete Database on one of the Existing Databases then Use Database on the database that is close to the deleted database'
3. Scroll down to 'The name of the database'
4. See the database name

**Expected behavior**
It should have run the database that I have clicked on and not on the already deleted database

**Screenshots**
![image](https://user-images.githubusercontent.com/99312804/166105186-b19f058a-0d25-44e5-be81-9ec67934fef4.png)

*Desktop (please complete the following information):*
 - OS: Windows
 - Browser: Chrome
 - Version: 10

*Smartphone (please complete the following information):*
 - Device: Xiaomi Note 10
 - OS: Android
 - Browser Chrome
 - Version 9.0
 - 
**Additional context**
The problem would be automatically fixed when you closed and rerun the application. But casual signin and signout did not fixed the problem for me.

**Comment by BeepBoopBit** [comment]
The said problem was caused by the problem solved in pull request #29
