### ISSUE TITLE
Add Column Window (Create Table Button)

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/CRUD-PROJECT#22]
**Describe the bug**
Whenever I try to create a table then click submit for the new columns. The table and columns fails to be added. 

**To Reproduce**
1. Go to 'A database'
2. Click on 'Create Table then finish the process of creating and click on submit'
3. It would exit you out of the application
4. Scroll down to 'the database that you have entered the new table'
5. See error

**Expected behavior**
It should have added the newly created table to the database

**Screenshots**
![image](https://user-images.githubusercontent.com/99312804/166105913-cd4499bc-0b79-4857-a693-907a59a39e79.png)

*Desktop (please complete the following information):*
 - OS: Windows
 - Browser: Chrome
 - Version: 10

*Smartphone (please complete the following information):*
 - Device: Xiaomi Note 10
 - OS: Android
 - Browser Chrome
 - Version 9.0

**Additional context**
I tried to rerun the application then signin and signout but it does not fix the problem. But all of the buttons rather than the submit button seems to work perfectly.

**Comment by BeepBoopBit** [comment]
tried to reproduce the bug, but can't reproduce it

![image](https://user-images.githubusercontent.com/90445232/166130526-90317e24-7fab-495f-bdf6-8f30001bd4d4.png)

Everything works perfectly fine, however, The information tab was not updated, I'll create an issue for it

**Comment by BeepBoopBit** [comment]
The problem will continue at #30. Please reopen and provide more details on how to reproduce the said problem again if ever that the problem persist.
