### ISSUE TITLE
Accumulating new tables

### ISSUE THREAD

**Issue by dreyoji** [BeepBoopBit/CRUD-PROJECT#24]
**Describe the bug**
The attributes of the new tables accumulate to the content of the first newly created table. If the new tables are deleted, it's attributes are still in the  first newly created table. If the first newly created table is deleted, the attributes of it will change the attribute names of the table before it.

**To Reproduce**
1. Go to 'Create Table' then make a table with attributes of different names (Hello1, Hello2, etc.).
2. After being returned to the CRUD window, look at the contents of the new tab. It should have no content as per the other issue.
3. Make another table by going to 'Create Table' then make a table with attributes of different names (Hello3, Hello4, etc.).
4. After being returned to the CRUD window, look at the contents of the new tab. It should have no content, but the attributes of the recent table should have been accumulated on the first newly created table.
5. If you delete the recently created table, its attributes should still be on the first created table.
6. If you delete all the newly created tables, the table before the first newly created table should have been affected by having different column names.

**Expected behavior**
The attributes of the newly created tables should be on their specific tables and not accumulate only on the first created table.

**Comment by BeepBoopBit** [comment]
I don't really understand the procedure, please simplify... Is it connected to the issue #32. Reopen if not
