### ISSUE TITLE
Grouping Select Properties

### ISSUE THREAD

**Issue by paulreonal** [BeepBoopBit/CRUD-PROJECT#28]
**Describe the bug**
In the grouping window, the selected attributes from the previous table show up even from the new selected table.

**To Reproduce**
1. Go to the CRUD window and select a table.
2. Click on 'Group'
3. Select attributes to display, then click 'Confirm'.
4. After the display, do not remove the selected attributes, then switch tables.
5. Click on 'Group' with the new selected table.
6. See error

**Expected behavior**
The selected attributes from the previous table should not be shown to the selected attributes of the current table.

**Desktop (please complete the following information):**
 - OS: Window
 - Browser: Chrome
 - Version: 11

**Comment by BeepBoopBit** [comment]
Fix at #37
