### ISSUE TITLE
'Create Database' window does not open properly

### ISSUE THREAD

**Issue by paulreonal** [BeepBoopBit/CRUD-PROJECT#39]
**Describe the bug**
'Create Database' window does not open. It only opens after selecting a database and clicking 'Use Database'.

**To Reproduce**
1. Go to 'Databases'
2. Click on 'Create Database'
3. Select a Database
4. Click on 'Use Database'
5. See error

**Expected behavior**
A new database should show up on the display.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 11

**Additional context**
Even if you try to create a database with the error, the newly created database does not show up.

**Comment by BeepBoopBit** [comment]
Already fix at #19
